In [15]:
import numpy as np
print(np.full((3,3),1,dtype=bool))
print(np.full((3,3),False,dtype=bool))
print(np.full((3,3),0,dtype=bool))
print('\n')
print(np.full((9), True, dtype=bool))
print(np.full((9), True, dtype=bool).reshape(3,3))
print('\n')
print('using Ones print bool: \n', np.ones((3,3), dtype=bool))
print('\n')
print(np.ones((9), dtype=bool))
print(np.ones((9), dtype=bool).reshape(3,3))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]
 [False False False]]
[[False False False]
 [False False False]
 [False False False]]


[ True  True  True  True  True  True  True  True  True]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


using Ones print bool: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


[ True  True  True  True  True  True  True  True  True]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [19]:
arr = np.arange(10)
arr
# or 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,13,14,12,15,16,17,18,222,233,3433,35,67])
arr[arr%2==1]

array([   1,    3,    5,    7,    9,   11,   13,   15,   17,  233, 3433,
         35,   67])

In [22]:
#replace all odd numbers in arr with -1
arr[arr%2==1]=368
arr[arr==368]=-1
arr

array([ -1,   2,  -1,   4,  -1,   6,  -1,   8,  -1,  10,  -1,  -1,  14,
        12,  -1,  16,  -1,  18, 222,  -1,  -1,  -1,  -1])

In [24]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr = np.arange(10)
out = arr.copy()
out[out%2==1]=-1
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])
arr = np.arange(10)
arr = arr.reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2, -1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [39]:
# Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
print(np.repeat(a,3))
print(np.tile(a,3))
print(np.r_[np.repeat(a,3), np.tile(a,3)])
print(np.hstack([np.repeat(a,3), np.tile(a,3)]))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [41]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8,3])
np.intersect1d(a,b)

array([2, 3, 4])