In [ ]:
import numpy as np

In [4]:
import pandas as pn

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
print(np.__version__)

2.2.2


In [7]:
#use tuple to create numpy array
arrTp = np.array((1,2,3,4,5,6,7))
print(arrTp)
print(type(arrTp))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [8]:
arr= np.array([[1,2,3], [4,5,6]])

In [9]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
arr3=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


In [11]:
print(arr3.ndim)

3


In [13]:
print(arr.ndim)

2


In [14]:
arr5= np.array([1,23,4,5,56,6], ndmin=5)

In [15]:
print(arr5.ndim)

5


In [18]:
print(arr[1])

[4 5 6]


In [17]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
print(arr5[0])

[[[[ 1 23  4  5 56  6]]]]


In [23]:
print(arr5)

[[[[[ 1 23  4  5 56  6]]]]]


In [25]:
print(arrTp[2] + arrTp[3])

7


In [26]:
print(arrTp)

[1 2 3 4 5 6 7]


In [27]:
print(arrTp[0]+arrTp[4])

6


In [28]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [30]:
print(arr[0,1])
arr[1,2]

2


np.int64(8)

In [32]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [36]:
arr3[0,1,2]

np.int64(6)

In [37]:
arr3.ndim

3

In [38]:
print(arr3[::-1])

[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [40]:
print(arr3[1,0:2])

[[ 7  8  9]
 [10 11 12]]


In [44]:
print(arr3.shape)
print(arr3.size)
print(np.size(arr3))
print(arr3.dtype)

(2, 2, 3)
12
12
int64


In [48]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.ones((9,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
np.full(4, 8, dtype=int)

array([8, 8, 8, 8])

In [53]:
np.full((8,5), "bapdada", dtype=str)

array([['b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b']], dtype='<U1')

In [54]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(9).reshape(3,2)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1]:
print("Hello world")

Hello world


In [7]:
arr = input().strip().split(' ')
print(arr)
arr[::-1]

['1', '2', '6', '7', '8', '3', '9', '41']


['41', '9', '3', '8', '7', '6', '2', '1']

In [18]:
import numpy
def arrays(arr):
    arr2 = numpy.array(arr,dtype=float)
    return arr2[::-1]
arr = ['1', '2', '6', '7', '8', '3', '9', '41']
result = arrays(arr)
print(result)

[41.  9.  3.  8.  7.  6.  2.  1.]


In [1]:
import numpy as np
arr = ['1', '2', '6', '7', '8', '3', '9', '41']
np.array(arr, dtype=float)
np.flip(arr)
print(np.flip(arr))

['41' '9' '3' '8' '7' '6' '2' '1']
